version: '3.1'

services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: "root"
        ports:
            - "5432:5432"
        volumes:
            - .:/docker-entrypoint-initdb.d
            - ./service-data:/var/lib/postgresql/data
    nats:
        image: nats-streaming
        ports:
            - "4222:4222"
            - "8222:8222"
        volumes:
            - "./nats-streaming:/data"
